<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-5D2VBBGP" failures="1" tests="1" name="Test" time="4.525" errors="0" timestamp="2024-08-09T17:28:58 IST">
  <testcase classname="testCases.Tc_003_LoginDDT" name="verify_loginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.IllegalArgumentException: The workbook already contains a sheet named &amp;apos;Test&amp;apos;">
      <![CDATA[java.lang.RuntimeException: java.lang.IllegalArgumentException: The workbook already contains a sheet named 'Test'
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.IllegalArgumentException: The workbook already contains a sheet named 'Test'
at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:1000)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:944)
at utilities.ExcelUtils.getrowCount(ExcelUtils.java:33)
at utilities.DataProviders.getData(DataProviders.java:17)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_loginDDT -->
</testsuite> <!-- Test -->
